server :
  port : 9090
# Credentials which clients need to use to connect
# To the admin server
spring :
  application:
    name : sba
  security:
    user:
      name: admin
      password: admin-password

# SMTP Server for local notifications
#  mail:
#    host: localhost
#    username: smtp-server-user
#    password: smtp-server-password

# Sender email address
  boot:
    admin:
      notify:
        mail:
          from: "Spring Boot Admin <noreply@foo.com>"
          # Comma-delimited list of recipient email addresses
          to: alice@foo.com,bob@bar.com
          # Comma-delimited list of carbon copy recipient email addresses
          cc: joe@foo.com

eureka:
  instance :
    preferIpAddress : true
    hostName : localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: true