server :
  port : 9090
# Credentials which clients need to use to connect
# To the admin server
spring :
  application:
    name : sba
  security:
    user:
      name: admin
      password: admin-password

# SMTP Server for local notifications
#  mail:
#    host: localhost
#    username: smtp-server-user
#    password: smtp-server-password

# Sender email address
  boot:
    admin:
      notify:
        telegram :
          enabled : true
          auth-token : 12345
          chat-id : 125995494
          disable-notify : false
          parse_mode : 'HTML'
          #apiUrl : https://api.telegram.org
          message : "<strong>#{instance.registration.name}</strong>/#{instance.id} is <strong>#{instance.statusInfo.status}</strong>"
          #message : "#{application.name} (#{application.id})\nstatus changed from #{from.status} to #{to.status}#{health[0] != null ? ('\n\n'+ indicator[0] + ' health indicator is ' + health[0] ) : ''}\n\n#{application.healthUrl}"
        mail:
          from: "Spring Boot Admin <noreply@foo.com>"
          # Comma-delimited list of recipient email addresses
          to: alice@foo.com,bob@bar.com
          # Comma-delimited list of carbon copy recipient email addresses
          cc: joe@foo.com

eureka:
  instance :
    preferIpAddress : true
    hostName : localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: true

logging :
  level :
    org.springframework.web.client.RestTemplate : DEBUG