#============================================================================
# SERVER
#============================================================================
server :
  port : 8082
#============================================================================
# SPRING
#============================================================================
spring:
  boot:
    admin:
      client:
        url : http://localhost:9090
  application:
    name : client-1
  management:
    security:
      enabled: false

#============================================================================
# LOGGER
#============================================================================
#logging:
#  config: classpath:logback-spring.xml
#  file : ${log.file.path}
#  level:
#    com.telkomsigma.kf.itemmanager: DEBUG
#  api :
#    base-path : http://localhost:9001
#============================================================================
# LOG FILE
#============================================================================
#log :
#  file :
#    path : /log/app/item-manager.log
#============================================================================
#EUREKA
#============================================================================
eureka:
  instance :
    preferIpAddress : true
    hostName : localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

#============================================================================
#INFO
#============================================================================
info:
  app:
    name: Client Application
    description: Client API within Microservices System
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"